### ISSUE TITLE
flow reversal simplification in conservationEquation

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#216]
When the flow never reverses (ie ```allowFlowReversal = false```) equations can be simplified. This is currently not being done for the enthalpy calculations in ```ConservationEquation``` since ```semiLinear()``` is not being used. See section 8.9.5 in Dymola User Manual Volume 2 for more information.

I'll propose a fix that changes the implementation, allowing such non-linear systems to be simplified.

**Comment by Mathadon** [comment]
Using this change I managed to decouple a non-linear system of:
```
Sizes of nonlinear systems of equations: {7, 7, 7, 357}
Sizes after manipulation of the nonlinear systems: {2, 2, 2, 40}
```
into
```
Sizes of nonlinear systems of equations: {7, 7, 7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18}
Sizes after manipulation of the nonlinear systems: {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
```

**Comment by mwetter** [comment]
@Mathadon :

Did you check with the dynasim support why these simplifications are not also done if the `actualStream` operator is used? This would be more elegant to be handled by the symbolic processor.

Could you please also commit a small test case that illustrates the behavior? This way we can keep it with the regression tests.

Regardless, as the current Dymola version does not seem to handle this case, I suggest to add such a change to the `master`. However, a few changes should be done:
- the same should be applied to all other stream properties, not just to `h_outflow`.
- I suggest some construct like
```
  if allowFlowReversal then // or in view of the comment below "if allowFlowReveral and (massDynamics == ...SteadyState) then "
   .... // use actualStream, as this is the preferred implementation
 else
  ... // use semiLinear for this special case
end if
```
   This way, we can keep the stream concept where it makes sense, and fall back to using semiLinear for the special case.
- Your implementation seems incorrect if `massDynamics != Modelica.Fluid.Types.Dynamics.SteadyState`. If `medium.d` changes, then the mass in the volume changes and you can have flow reversal. Maybe the fluid volume should be such that the volume expands, rather than the mass? Or alternatively, `massDynamics` should by default be set to `energyDynamics` unless `allowFlowReveral=true`, in which case it should be steady state?

**Comment by Mathadon** [comment]
Hi @mwetter 

I checked with Claytex and they say (that the developers say) that it's only supported for semiLinear(), but that a flag may be added in the future for supporting this in other functions.

I can add an example but since the change does not affect numerical results it makes no sense to add a unit test per se. 

I tried adding the same changes for the other stream properties, but this results in an error:
```
The operator inStream is not supported in this context.
```
for 
```
ports_mXi_flow[i,:] = semiLinear(ports[i].m_flow, inStream(ports[i].Xi_outflow),ports[i].Xi_outflow) 
```
note that allowFlowReversal is not defined at the level of the ```ConservationEquation```. The simplification occurs because of the min/max attribute in the fluid ports connected to the ```ConservationEquation```.
Can you explain what the difference is between the new implementation and the ones using ```actualStream```? As far as I know they are identical from a mathematical point of view.

I would not say that the implementation is incorrect for compressible media, rather that it has an important limitation to consider when using the option. Note that water is incompressible so this would not create any problems. For compressible media it may be useful to add ```assert``` statements to avoid simulating very wrong things? I think the current implementation is ok, but I should probably add a word of caution in the documentation.

I'll try to add an example and update the documentation. Can you let me know if you agree to the above?

**Comment by mwetter** [comment]
An example would be good. In the future, it may be worthwhile to expand the unit tests so that also the number of nonlinear/linear equations are recorded with the results.

Regarding `operator inStream is not supported` did you try to make a loop over `Medium.nXi`? It would be odd to having to mix `actualStream` and `semiLinear(... inStream(...` when both codes intend to do the same.

The paper https://www.modelica.org/events/modelica2009/Proceedings/memorystick/pages/papers/0078/0078.pdf 
says that `actualStream` is a short-hand notation for `semiLinear` and `inStream`, but because you need to expand this in your model, I am not sure whether this is what tools implement.

We should detect in an `initial equation` section whether the model parameters are valid for the selected medium. Running a simulation that suddenly asserts is not a good solution, and users are not likely to read documentation.... I think we should still discuss the issue of constant volume vs. constant mass with the library group.

When would you want `massDynamics != energyDynamics`? I have not yet found a good application for that.

**Comment by Mathadon** [comment]
Looping over nXi and nC works, thanks for the tip!

The paper you reference states:
```
The actualStream operator used to define the energy balance is a shorthand notation for:
actualStream(port.h_outflow) == if port.m_flow > 0 then
inStream(port.h_outflow) else port.h_outflow;
```
I cannot find ```semiLinear``` being mentioned in the paper.

When looking at dsmodel.c for ```Annex60.Fluid.MixingVolumes.Examples.MixingVolumeHeatConduction``` with the original implementation I get:
```
helpvar[3] =  -W_[31] > 0.0;
W_[166] =  -W_[31]*(IF helpvar[3] THEN 65591.745 ELSE W_[104]);
...
helpvar[8] = W_[31] > 0.0;
W_[167] = W_[31]*(IF helpvar[8] THEN 55446.345 ELSE W_[104]);
```
and with the new:

```
helpvar[0] = W_[31] >= 0;
helpvar[2] = helpvar[1] >= 0;
W_[167] = IF helpvar[0] THEN 55446.345*W_[31] ELSE W_[104]*W_[31];
  W_[166] = IF helpvar[2] THEN (-65591.745)*W_[31] ELSE  -W_[104]*W_[31];
```
so the implementation seems to be almost the same in c-code. I cannot see any case where both implementations would not be mathematically identical. This is a simple example of course.. Note that the new implementation seems to be a bit more efficient since less help variables ```helpvar``` seem to be generated.

What do you mean with model parameters not being 'valid'? 

I have applications where ```massDynamics != energyDynamics``` but I rather not discuss this here.

**Comment by mwetter** [comment]
I meant `actualStream`, not `semiLinear`, sorry for the confusion.

By model parameters not being valid I mean a combination of medium package and settings for the mass and energy balance. We can discuss your application offline (or at the Annex 60 meeting). I was even thinking about setting `final massDynamics=energyDynamics` (or removing the `massDynamics` parameter) so it would be interesting to understand what your application is and what would motivate different settings. What does it mean if mass is governed by an ODE but not energy, or vice versa?

The new implementation only saves a boolean variable, so this won't translate into a measurable reduction of computing time in this simple example.

**Comment by Mathadon** [comment]
I added an example in a new package. I did not add a unit test since the Newton solver in the model does not even converge. 
I think the rest of this discussion can be continued later since it has a broader impact on design decisions of the library.

**Comment by mwetter** [comment]
This is now on the master.
