### ISSUE TITLE
Add Airflow package to Annex 60

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#246]
Picking up again on the airflow benchmark in #82, it seems to make most sense to add Buildings.Airflow to Annex 60 and then adjust the benchmark to use the up-to-date version of Annex60.Airflow. After including the package into Annex 60, I would merge that into the benchmark branch and finish the benchmark design.

@Mathadon and @thorade : Are there objections from your side to include Buildings.Airflow in Annex 60 as a whole?

**Comment by Mathadon** [comment]
I have two remarks:
1) we'd have to review all code thoroughly but if you're up for that then that's ok for me ;)
2) It's not clear to me how important this inter-zonal air flow is and to what level it should be detailed. The current pressure-based approach can load to very demanding calculations. I'm wondering if it's not better to approach this thermally by defining some temperature-dependent resistance between zones.

**Comment by mwetter** [comment]
@Mathadon : Regarding 2, the dominant driving force for air exchange among room and between the room and the outside is typically wind pressure, flow imbalance and stack effects. These would not be captured by a temperature dependent resistance (if I understand your concept correctly). Also, we need to move air and not just sensible heat between zones in order to transport humidity and contaminants.
The scalable benchmark is meant to test the nonlinear solver and the model implementation.

**Comment by Mathadon** [comment]
I agree that the temperature dependent resistance would not work. I have no further objections :)

**Comment by thorade** [comment]
I do not know what is in that package. If you think it is a valuable addition for all libraries go ahead and add it. If it used for benchmarking only (and for nothing else) then we could discuss to move it to Experimental or to introduce a new package/directory Benchmark that is not merged into the inheriting libraries (like Obsolte and Experimental).

**Comment by mwetter** [comment]
@marcusfuchs : OK to merge `Airflow` into separate branch, and then into master after it has been reviewed.
