### ISSUE TITLE
Add glycol solutions

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#25]
Glycol and brine solutions should be added to `Annex60.Media`. As a basis, the file therPro.nmf should be used.

Before starting the implementation the following questions need to be answered.

1. Should cp really be a polynomial or can it be assumed to be constant in the fluid temperature? Using a non-constant value would complicate the implementation (and the overhead for the computations) considerably as the enthalpy will be a polynomial in temperature, which cannot be inverted symbolically. See for example `Modelica.Media.Incompressible.TableBased.T_ph`.
2. therPro.nmf contains 12 liquids in addition to water. Which ones do we need? If we need more than one, we may as well implement all of them by converting the tables automatically.
3. Regarding pre-compiled models, would we need to allow users to change TFreeze _after_ the model is compiled, or do we precompile a library for certain permutations of liquid types and TFreeze? If it is the later, what are these permutations? If TFreeze can be fixed at compile time (e.g., it is a Modelica constant, not a parameter), then we can simplify the polynomials to be 3rd order polynomials (e.g., 4 terms in TAve^n), otherwise we have a mixed coefficient polynomials with 19 terms. 
The problem with this point is that if TFreeze is a constant, then we can do a lot of simplifications (e.g., evaluate the mixed coefficient terms and collect the coefficients for the polynomial to be a function of TAve only). If TFreeze is a parameter, then this is not possible. In fact, it is not clear how to implement this as Modelica functions (such as for computing the enthalpy) can only access constants, but not parameters.

**Comment by mwetter** [comment]
Closed until work on implementing glycol starts again.
Temperature dependent properties may not be needed if the constants T_ref are set in the media.

**Comment by mwetter** [comment]
Reopened issue due to https://github.com/iea-annex60/modelica-annex60/issues/478 (which I closed to move the discussions to this thread).

I agree that a glycol implementation will be needed.

Buildings has no glycol implementation.
The MSL has an implementation of Glycol47 (which has a fixed concentration).

**Comment by Mathadon** [comment]
So far I am using glycol by just extending the water medium with different constant thermal properties:

```
package ConstantPropertyGlycol20Water 
  "Package containing properties for water with 20% glycol"
  import Buildings;
  extends Buildings.Media.Water(
  cp_const=3880,
  d_const=1033,
  lambda_const=0.505,
  T_min=Modelica.SIunits.Conversions.from_degC(-8));
  // source: https://detector-cooling.web.cern.ch/detector-cooling/data/Table%208-3-1.htm
end ConstantPropertyGlycol20Water;

```

**Comment by damienpicard** [comment]
@Mathadon any reason why you don't extends Annex60.Media.Water instead of  Building.Media.Water? I could indeed use such a simplified approach.

@mwetter regarding the previous conversation: I understand that being able to change the concentration after compilation is useful for FMU and IDA-ice. However, it seems to me that this is a technical problem which can either be solved by some (small) reformulation of the code, or by more flexibility on the solver side. I would therefore be in favour of adding the Media to the library even if not all parameters/constants can be changed after compilation and to try later on to solve these issues. That would move us a step closer and it might clarify what the technical problem is. Furthermore, making new types of Medium available which are not available in other modelica library is a substantial added value for Annex 60.

Let me know if I can help here.

**Comment by mwetter** [comment]
@damienpicard : I am fine with having the medium fixed at compilation time because the current implementation of `Modelica.Media` does not seem to allow a change in concentration after compilation. 

However, rather than implementing glycol with a fixed concentration, it would be worthwhile to spend a couple of hours to see how the concentration could be set by a constant and properties such as `cp_const` be computed based on this constant. This way, we can provide something like 
```
package ConstantPropertyGlycol20Water
  extends ConstantPropertyGlycolWater(concentration = 0.2);
```

**Comment by damienpicard** [comment]
@mwetter the following method seems to work:

```
package Air
   record constantProperties
        parameter Density dStp = 1.2;
   end constantProperties;

redeclare function density "Gas density"
  extends Modelica.Icons.Function;
  input ThermodynamicState state;
  output Density d "Density";
  parameter constantProperties c;
algorithm 
  d :=state.p*c.dStp/pStp;
end density;
end Air;
```

Calling the medium with variable properties can now be done by: `redeclare package Medium = IDEAS.Media.Air(constantProperties (dStp=1.2))`.

Does this solve the problem? Of course, instead of the density, the concentration should be used and the density calculated accordingly.

**Comment by mwetter** [comment]
@damienpicard 
Yes, this is the pattern I was thinking about. Then, we could do few predefined media such as
```
package ConstantPropertyGlycol20Water
  extends ConstantPropertyGlycolWater(concentration = 0.2);
annotation(....);

package ConstantPropertyGlycol40Water
  extends ConstantPropertyGlycolWater(concentration = 0.4);
annotation(....);
....
```
Key will be to implement `ConstantPropertyGlycolWater` in such a way that all properties are computed correctly based on `concentration`.

**Comment by damienpicard** [comment]
@mwetter hopefully the properties of `therPro.nmf` are expressed as a function of the concentration? Where can this file be found? The implementation of `ConstantPropertyGlycolWater` should be similar (but easier) than for humid air, as the concentration is not a variable but a parameter.

**Comment by mwetter** [comment]
@damienpicard I will forward you an email with the file
