### ISSUE TITLE
Types as directory or .mo

### ISSUE THREAD

**Issue by thorade** [iea-annex60/modelica-annex60#253]
We want to start running the scripts for integrating Annex60 into BuildingSystems more frequently. In that context we are also trying to streamline the file/package structure of our library to the Annex60 structure. 
In Annex60, there are currently two ways where Types are stored, 
see `Annex60/Types/package.mo` versus `Annex60/Fluid/Types.mo`. 
From the [Annex60 Style Guide](https://github.com/iea-annex60/modelica-annex60/wiki/Style-Guide) it is not clear to me what way is preferred. Does it depend on the level? 
Is automatic merging of libraries possible with a single file `Annex60/Types.mo`?

**Comment by mwetter** [comment]
`Annex60/Types/package.mo` is used because there are sub-packages with type
definitions. I think this is the preferred way, although as you point out,
in `Fluid/Types` all are in one file which will make it harder to merge.

There are different `Types` packages as `Fluid/Types` is only used in
`Fluid`, where as `Annex60/Types` is used in different packages of the
top-level package.

**Comment by mwetter** [comment]
Closed since BuildingSystems updated its directory structure.
