### ISSUE TITLE
various examples fail pedantic model check and translation in Dymola 2016

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#266]
`Examples.MixingVolumes` fails the pedantic model check in Dymola 2016 because `PartialMixingVolume` accesses the conditionally removed component `dynBal`, and because of a redeclaration of the `ThermodynamicState` in the media.

**Comment by mwetter** [comment]
Reopened as more changes are needed to make pedantic model check and translation work in `Buildings`.

**Comment by mwetter** [comment]
@marcusfuchs : Can you please corrected the benchmarks so that the files below simulate if you enable the pedantic modelica check in Dymola:
```
Resources/Scripts/Dymola/Experimental/Benchmarks/AirFlow/Examples/MultipleFloorsVectors.mos
Resources/Scripts/Dymola/Experimental/Benchmarks/AirFlow/Examples/ZoneStepResponse.mos
Resources/Scripts/Dymola/Experimental/Benchmarks/AirFlow/Examples/TwoFloors.mos
```
This seems to be the only outstanding issue to enable pedantic mode. The problem seem to be that different start values are used at the same object hierarchy.

**Comment by marcusfuchs** [comment]
I added some start values to solve this issue and it should now work.

Yet, the problem causing this seems to be a fundamental inconsistency within the MSL regarding these start values. As I understand it, the problem is caused by different start values for the medium temperature and for heat ports that are coupled with each other via connect statements. In this case, `Annex60.Media.Air` sets `Temperature(start=T_default)`, with `T_default` being set in `Modelica.Media.Interfaces.PartialMedium` to `293.15 K`. At the same time, the type `Modelica.SIunits.Temperature` takes the start value from `ThermodynamicTemperature`, which is `288.15 K`. Thus, setting any temperature with this type will be in conflict with any medium temperature. 

Is this interpretation correct or am I making an error in the model design?

**Comment by mwetter** [comment]
@marcusfuchs : Your interpretation is correct. I don't see a better work-around than manually  setting consistent start values as setting Medium.T_default=288.15 K is not good either. I rather start the medium at room temperature.

I will issue a pull request.

**Comment by mwetter** [comment]
Closed as it is on the master.

**Comment by marcusfuchs** [comment]
Just as additional reference: The start value problem is already on the Modelica Issue Tracker here:https://trac.modelica.org/Modelica/ticket/1674

**Comment by Mathadon** [comment]
It's probably a good idea to reply in this topic that this is/was a problem for us?
