### ISSUE TITLE
Compressible air

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#310]
The current air implementation is compressible:
```
d/dStp = p/pStp;
```

This implies that a pressure state is created in mixing volumes. The physical significance of this for our purposes seems extremely small to me since the amount of energy contained by this 'variable' volume `V*dp_max/pStp * dStp` is very small compared to the air in the total value `V`, around 0.1%. 
A second effect of this state is an effect on numerics, it introduces a state and therefore can decouple non-linear algebraic loops. However it also introduces (very) small time constants, which can slow down simulations. 

The only real significance of whether or not to simulate compressible air is its effect on the solver. So we should probably optimise the implementation such that the solver is most efficient.  Based on my experience, using compressible air can imply a large penalty for the computation time. Therefore I'd suggest to make air incompressible. This is probably something we should discuss during the Annex meeting because I don't think we'll all agree. :)

**Comment by mwetter** [comment]
Did you try `Buildings.Obsolete.Media.GasesConstantDensity.MoistAirUnsaturated`? This has been made obsolete because the computing performance was not good in benchmarks.

**Comment by Mathadon** [comment]
I'll add a documentation section under ```Annex60.UsersGuide.ComputingTime```

**Comment by mwetter** [comment]
@Mathadon 
I revised your documentation. We should have a discussion on the next call where such documentation should best be. For `Buildings` we typically put such widely applicable information in the user guide http://simulationresearch.lbl.gov/modelica/userGuide/ which also has some information about pressure states (http://simulationresearch.lbl.gov/modelica/userGuide/workArounds.html#breaking-algebraic-loops), while documentation that is specifically to a model is in in the model's (or package's) user guide such as for the pumps and the sensors.

We should discuss where the numerics information should be so that users can easily find information in one place.
