### ISSUE TITLE
Airflow ducts

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#381]
We seem to miss (detailed) models for ducts, including things like bends, contractions, etc. Making models for each of these components and coupling them using connections seems cumbersome. Therefor I was thinking of making a single component that allows entering the parameters of multiple sequential (series) components in a flow network. For each component a `k` value can then be computed. These k values then simply need to be summed up to achieve a computationally efficient implementation of the pressure drop equation.

Is this something that will/can work properly?

**Comment by mwetter** [comment]
That should work. I suggest you also give the option to give as parameter the zeta values (and the diameter) as zeta values are often used for single resistances. 

I assume you will provide a parameter for `zeta` and not for "number of bends" as two bends right next to each other have a larger zeta value than the sum of the individual bends (due to the turbulence).

I think @nytschgeusen did quite some work in the past in this area.
