### ISSUE TITLE
Obsolete dynamicBalance parameter

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#411]
Some models (e.g. `Fluid.Movers.FlowControlled_m_flow`) still have a parameter `dynamicBalance` which overwrites `energyDynamics` and `massDynamics` if false.

I think the parameter is still there to be backwards compatible with older versions of the `Annex60` library, but it's my personal opinion that, as long as there is no official release version of the library, backwards compatibility should not be considered. In that case, i would suggest to remove the `dynamicBalance` parameter everywhere.

**Comment by Mathadon** [comment]
+1 :)

**Comment by mwetter** [comment]
I am in favor of removing `dynamicBalance` as I think it is clearer to simply have `energyDynamics`  and `massDynamics` rather than having a parameter overwrite the functionality of another parameter.

I will assign it to @rubenbaetens . Please also update the release notes of the models.

(I however think we should be careful to have backwards compatibility where meaningful as `Buildings` and maybe other libraries have official releases. Next month we plan to have a non-backwards compatible release of `Buildings.` Hence it would be good to get this change and any other non-backwards compatible changes done.)

**Comment by rubenbaetens** [comment]
We also plan to have a non-backward compatible release of `IDEAS` next month, so perfect timing here.

**Comment by rubenbaetens** [comment]
Following models still contain the `dynamicBalance` parameter:

- [ ] `Annex60.Fluid.Movers.BaseClasses.PartialFlowMachine`
- [ ] `Annex60.Fluid.BaseClasses.PartialThreeWayResistance`

**Comment by Mathadon** [comment]
Closed in #412
