### ISSUE TITLE
MixingVolumeZeroFlow tests for accuracy of 1E-60

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#441]
The model `Annex60.Fluid.MixingVolumes.Validation.MixingVolumeZeroFlow` fails to simulate in OpenModelica because the asserts

```
  assert(abs(volNonLinSys.heatPort.Q_flow)<Modelica.Constants.small or time<1,
    "Heat flow leakage around zero flow.");
  assert(abs(volLinSys.heatPort.Q_flow)<Modelica.Constants.small or time<1,
    "Heat flow leakage around zero flow.");
```

are too strict. The message is

```
assert            | warning | The following assertion has been violated at time 1.000400
|                 | |       | abs(theRes.Q_flow) < 1e-60 or time < 1.0
assert            | error   | Heat flow leakage around zero flow.
```

This test needs to be less strict to allow for rounding errors or numerical approximation to solutions (assuming that there is no closed solution, which I did not verify).

**Comment by Mathadon** [comment]
I guess this is similar to https://github.com/iea-annex60/modelica-annex60/issues/439 where the algebraic system solver is also unable to find the exact solution of the algebraic loop. It makes sense that 1E-60 is then too small since the accuracy of the algebraic loop solver (in Dymola) seems +- half the machine accuracy, resulting in errors of ~1e-7. Are these also the kinds of values you get?

**Comment by mwetter** [comment]
@Mathadon To be able to also simulate these tests with other tools than Dymola, we should relax the assert to have an accuracy that is one -- or probably better two -- orders of magnitude less than the solver tolerance. 
Alternatively, we could remove the assert and plot the expected solution (or the difference of two alternate calculations if they should be equal) which then becomes part of the reference test.

**Comment by agnesramle** [comment]
We do also see the same problem when simulated with JModelica.
