### ISSUE TITLE
Mass-flow in movers when dp- or y-signal equals zero

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#457]
At this moment, pressure- or speed-controlled movers may still have a mass-flow even when the input-signal equals zero. In reality, a pump will act as a closed valve when the control signal asks the pump to be inactive while a fan will have a leakage when pressure drops occur. Should we include this behaviour, or how is this best approached ?

The issue is shown well in `Fluid.Movers.Examples.PumpsParallel` where a massflow occurs in `floMac1` when `y=0`.

**Comment by Mathadon** [comment]
This is intended functionality as far as I know. I'm unaware of pumps behaving like a closed valve when they are 'off'? If you want `m_flow=0` then I suggest to put a valve in series with the pump.

**Comment by rubenbaetens** [comment]
But then by default there is also no pressure drop assumed

**Comment by mwetter** [comment]
@rubenbaetens 
There is a small pressure drop for numerical reasons in the mover model, see
http://simulationresearch.lbl.gov/wetter/download/2013-IBPSA-Wetter.pdf
page 3510, condition 3.(c).
I prefer to leave it as is because any changes would need to be carefully examined to make sure that we don't introduce a singularity near zero flow.
