### ISSUE TITLE
Inclusion of Buildings.Fluid.FMI 

### ISSUE THREAD

**Issue by tsnouidui** [iea-annex60/modelica-annex60#472]
This issue is to discuss whether `Buildings.Fluid.FMI`should be included in the Annex60 library. 
This is a package which Activity 1.2 was planning to reference in the report. Best might be if the reference was pointing to the Annex60 library as opposed to the Buildings library.
This might also be relevant for potential future work done in the IBPSA project 1.

**Comment by marcusfuchs** [comment]
I think this would be a good addition to the library.

**Comment by mwetter** [comment]
@Mathadon @thorade @mlauster @marcusfuchs 
Can you please have a look at `Buildings.Fluid.FMI` on the master so we can discuss in Corsica whether to include this, keep it open with a plan for when to make a decision, or close it and do not include it.

**Comment by Mathadon** [comment]
I had a look at the package. I have a few remarks.

Small inconsistency:

```
Buildings.Fluid.FMI.Interfaces.MassFractionConnector X_w if 
       Medium.nXi > 0 "Water vapor mass fractions per kg total air";
  Medium.ExtraProperty C[Medium.nC] "Properties c_i/m";
```

I.e. `X_w` is conditional but `C` is not? Why not export `Xi` instead of `X_w`? Using `T` instead of `h` may lead to conservation of energy issues when using more complex media.

Why is there a dedicated connector `Buildings.Fluid.FMI.Interfaces.PressureInput` for the pressure and not for other variables?

Would it be possible to have an example where an example is exported as an FMU, then imported again as an FMU in a different model? Ideally this model could compare results of the FMU and the 'true' Modelica model.

Other than that I see no reason not to add the model.

**Comment by mwetter** [comment]
- [ ] Fluid.FMI.Adaptors.Inlet should use PressureOutput connector not Real connector.

**Comment by mwetter** [comment]
@Mathadon 
1. use cases are explained in `Annex60.Fluid.FMI.UsersGuide`.
2. We use `X_w` but `C[:]` as there is only one possible mass fraction (for moisture) but there can be any number of trace substances. If we were to use `Xi[:]`, then the FMU would have a vector of inputs and outputs but the size of this vector could only 0 or 1, which I think is less convenient than simply having a scalar variable.
3. There is a `Fluid.FMI.Interfaces.PressureInput` (and `PressureOutput`) because this is needed not only as part of the `Inlet` and `Outlet` composite connectors, but also as a separate connector in `FMI.Adaptors.Inlet` and `FMI.Adaptors.Outlet`.

@thorade @Mathadon 
This is ready for final review and merge to the `master`. Are you both OK with adding this package, in which case we can assign someone (or multiple people) for review.

**Comment by thorade** [comment]
Yes, this can be added!
If we do not like later, we still have the possibility to excleude it in the merger script.

**Comment by Mathadon** [comment]
ok :)
