### ISSUE TITLE
DeltaM and ReC variables

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#480]
We currently have the following parameters in `Annex60.Fluid.FixedResistances.FixedResistanceDpM`:

```
  parameter Boolean use_dh = false "Set to true to specify hydraulic diameter";
  parameter Modelica.SIunits.Length dh=1 "Hydraulic diameter";
  parameter Real ReC(min=0)=4000 
    "Reynolds number where transition to turbulent starts";
  parameter Real deltaM(min=0.01) = 0.3 
    "Fraction of nominal mass flow rate where transition to turbulent occurs";
```

I have two remarks:
- The only use of these parameters is to determine when the regularisation around zero flow is activated, which has a limited effect on model results. Still these parameters are prominently present in the parameter window, suggesting their values should be chosen well. I propose to move those parameters to a different tab.
- The default values of these parameters (mostly deltaM) result in the regularisation region being activated quite quickly, already at 30% nominal flow. I would suggest to reduce this value drastically to 1e-4 or similar since there is really no reason to have such a broad regularisation region. Moreover it leads to 'wrong' results. This would require to also lower the minimum value of deltaM.
- `ReC` and `dh` give the impression that the flow function/model considers the existence of a 'turbulent' regime (and hence also a non-turbulent regime), which is not true since the flow is always turbulent, even in the regularisation region. Moreover it requires physical insight to know which diameter the user should provide, which can be confusing. Therefore we could even remove these variables.

**Comment by mwetter** [comment]
I (partially) agree with your remarks and suggest the following:

1. Rename `FixedResistanceDpM` to `FixedResistanceDpM_dh` which uses `dh`, `ReC` and `deltaM` and make a new model `FixedResistanceDpM` that does not use `dh`, `ReC` and `use_dh`. This allows to model ducts with `FixedResistanceDpM_dh` if users have information about `dh`. However, `dh` should _not_ be moved away from the main window, as this is an important value; otherwise if `dh=1` for a 3/8" pipe, you get really wrong behavior. Using a new model also allows us to _not_ provide a default value for `dh`. I believe we had a default value as otherwise there would be a warning if no value is assigned and `use_dh=false` but as the model is sensitive to this value which can vary largely, it would be better not to provide a default.
2. I disagree with setting `deltaM` to something like 1E-4 as for m_flow/m_flow_nominal < deltaM, the model approximates laminar flow, although it is not done with a linear function as it should be to be exact. This is also mentioned in https://github.com/iea-annex60/modelica-annex60/issues/444 and we could transition to a linear function in that region. If you propose to reduce `deltaM`, then please suggest a value using for example as a rule of thumb where we typically have laminar flow in pipes or ducts, maybe assuming for pipes `R_nominal = 100 Pa/m` and for ducts also a realistic R value (or design velocity).

**Comment by Mathadon** [comment]
But we do not approximate laminar flow, its a simple regulaisation?

**Comment by Mathadon** [comment]
I.e. A regularisation that ensures continuity.

**Comment by mwetter** [comment]
The transition is done in the laminar region but as I wrote ("...although it is not done with a linear function as it should be to be exact.") it should be done using a linear function to truly represent laminar flow. See also `Buildings.Fluid.BaseClasses.FlowModels.Validation.InverseFlowFunctions` to see that the regularized version is a better approximation of the laminar flow than a quadratic function with very small `deltaM` would be.

**Comment by Mathadon** [comment]
I forgot what we agreed here.. Will we remove 

```
  parameter Boolean use_dh = false "Set to true to specify hydraulic diameter";
  parameter Modelica.SIunits.Length dh=1 "Hydraulic diameter";
  parameter Real ReC(min=0)=4000 
    "Reynolds number where transition to turbulent starts";
```
?

**Comment by mwetter** [comment]
@Mathadon I thought in Corsica we said we implement the comment from June 16.
