### ISSUE TITLE
add validation criteria and missing source for figures for ROM VDI 6007

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#482]
@mlauster 

- [x] Can you please add the source file that was used to generate the figures in `Resources/Images/ThermalZones/ReducedOrder/RC`. If they are from a full paper that you may not want to share as LaTeX, it would be good to add at least these sections that generate the figures
- [x] Also, on Dymola 2017, I get different reference results for`Resources/ReferenceResults/Dymola/Buildings_ThermalZones_ReducedOrder_Validation_VDI6007_TestCase12.txt`
Maybe this is due to the change in numerics between Dymola versions, and the interpolation done by the regression tests. In either case, it would be good to add an `assert` if VDI prescribes a certain accuracy. Otherwise, it will be very cumbersome to ensure that once validated test cases remain within the required tolerance from one version of a tool to another, and also among different tools.

**Comment by mlauster** [comment]
@mwetter, the source file is a MS Visio .vsd file. 
You can choose from the following list of file formats, including .vsd . :smile: 

![unbenanntes bild](https://cloud.githubusercontent.com/assets/6892690/16330500/efd80d6a-39e9-11e6-8cc9-c97da029ab88.png)

**Comment by mwetter** [comment]
@mlauster : svg would be the preferred format as it is editable with open source tools on all major os.

**Comment by mwetter** [comment]
@mlauster 
- [ ] There is also some documentation missing in the package.mo files:
```
*** Error:  File '/ThermalZones/ReducedOrder/EquivalentAirTemperature/BaseClasses/package.mo' does not contain required string 'documentation'.
*** Error:  File '/ThermalZones/ReducedOrder/SolarGain/BaseClasses/package.mo' does not contain required string 'documentation'.
```

**Comment by mlauster** [comment]
@mwetter, in #94 you said, you have an exemplary implementation for asserting accuracy to validation cases, using `when` blocks in Buildings. Can you say where exactly this implementation is? I had a look at `Case600FF`, but couldn't find anything.

**Comment by mwetter** [comment]
@mlauster For the BESTEST in Buildings, we don't use assertions but rather plot the range of other results and use this in the regression tests.
For the VDI models, could you use the existing `AssertEquality` and set `t0`, or if this is not sufficient, add another parameter (possibly extending it in `ThermalZones.ReducedOrder.Validation.VDI6007.BaseClasses`)?

**Comment by mlauster** [comment]
@mwetter, I modified `AssertEquality` to consider three periods and added them together with `mean` to all validation cases, what works fine for eleven out of twelve test cases. Thanks for that hint!
The only problem is `TestCase11`, that incorporates heating and cooling:
- I need a control, because heating and cooling power are limited.
- I can use only one controller, because heating and cooling get active/deactivated at exactly the same temperature.
- Heating is convective and cooling is a surface cooling. Thus, the systems have a different inertia/dynamic. That makes it difficult to find control parameter that suit the quite strict thresholds of the VDI 6007-1. The VDI gives no information about control (they solve it iteratively in zero time steps).

In my former Python script, I used an output time step of 60 seconds, for what I could ignore the high but short overshoots of my controller. `Mean`in Modelica accounts for a continuous signal and I'm out of the bounds, at least for one time step (the exact time step depends on my control parameter). Does anyone has an idea how to cope with this problem?

Otherwise I propose to add the information above to the test case and leave out the `AssertEquality` for `TestCase11`.

**Comment by mwetter** [comment]
@mlauster 
Would it help to put a timer in `AssertEqualityThreePeriods` and whenever a boolean input signal changes, the assertion is not tested until x seconds lapsed since the boolean signal became true.
Then, you could use `Modelica.Blocks.Logical.Change` at the output of `GreaterThreshold1`.

Also, I suggest to add some hysteresis to this threshold as otherwise, the simulation could jam if conHeaCoo outputs zero +/- numerical noise.

**Comment by mlauster** [comment]
@mwetter , this wouldn't work because I need to check hourly mean values. So either I do not check the first hour after switching heating and cooling or I ignore the first x seconds for the hourly mean value of the respective hours. This implies replacing the heating or cooling power of the first x seconds of the respective hours by some artificial values because I can't tell the mean block to take only y-x values for some hours while keeping all for the remaining hours. I implemented a solution following the second approach, replacing the first 60 seconds with 100 Watt. In this way I can stay within the bounds. Is this solution fine for you?

**Comment by mwetter** [comment]
@mlauster 
Your approach looks good, but it can be simplified which I did on the branch `issue482_ROM_validation`, e.g., you only need one timer. I tested it on Dymola 2017.

Also, it would be easier to modify the model and have it look consistent if you expand the drawing area, as opposed to making the components smaller as the model gets bigger.

**Comment by mlauster** [comment]
@mwetter 
Thanks, that looks indeed a lot more elegant. I was a bit suspicious about `Modelica.Blocks.Logical.Change` because I couldn't evaluate when it switches to `True`. Now I'm convinced. :)
I changed `greaterThreshold1` to `hysteresis` to prevent chattering around zero for `conHeaCoo`.
