### ISSUE TITLE
Nominal trace concentrations

### ISSUE THREAD

**Issue by rubenbaetens** [iea-annex60/modelica-annex60#507]
The `Medium` package has a parameter `C_nominal` for trace concentrations, but this is never used. For example, the current implementation of `IDEAS.Fluid.Interfaces.LumpedVolumeDeclarations` states:

```
  parameter Medium.ExtraProperty C_start[Medium.nC](
       quantity=Medium.extraPropertiesNames)=fill(0, Medium.nC)
    "Start value of trace substances"
    annotation (Dialog(tab="Initialization", enable=Medium.nC > 0));
  parameter Medium.ExtraProperty C_nominal[Medium.nC](
       quantity=Medium.extraPropertiesNames) = fill(1E-2, Medium.nC)
    "Nominal value of trace substances. (Set to typical order of magnitude.)"
   annotation (Dialog(tab="Initialization", enable=Medium.nC > 0));
```

This however complexifies the use of e.g. CO2 in air where you want to set a default 400 ppm as starting value (now air volumes start at 0 ppm). I suggest to change this into:

```
  parameter Medium.ExtraProperty C_start[Medium.nC](
       quantity=Medium.extraPropertiesNames)=Medium.C_nominal
    "Start value of trace substances"
    annotation (Dialog(tab="Initialization", enable=Medium.nC > 0));
  parameter Medium.ExtraProperty C_nominal[Medium.nC](
       quantity=Medium.extraPropertiesNames) = Medium.C_nominal
    "Nominal value of trace substances. (Set to typical order of magnitude.)"
   annotation (Dialog(tab="Initialization", enable=Medium.nC > 0));
```

The same can be stated for e.g. `IDEAS.Fluid.Sources.Boundary_pT` which defines

```
  parameter Medium.ExtraProperty C[Medium.nC](
    final quantity=Medium.extraPropertiesNames) = fill(0, Medium.nC)
    "Fixed values of trace substances"
    annotation (Dialog(enable = (not use_C_in) and Medium.nC > 0));
```

whereas i propose to change this into

```
  parameter Medium.ExtraProperty C[Medium.nC](
    final quantity=Medium.extraPropertiesNames) = Medium.C_nominal
    "Fixed values of trace substances"
    annotation (Dialog(enable = (not use_C_in) and Medium.nC > 0));
```

**Comment by Mathadon** [comment]
+1

**Comment by mwetter** [comment]
I am more in favor of the current setting because of the following:

1. Implementing the change would yield wrong results in existing models that use the default. I don't think we can do a conversion script that guards against making changes to user models that would lead to different results.
1. If users combine models from `Modelica.Fluid` with `Annex60.Fluid`, they would get wrong results unless they remember that `Modelica.Fluid` uses 0, whereas `Annex60.Fluid` uses `C_nominal`.
1. The underlying issue is that `Modelica.Media.Interfaces.PartialMedium` defines `T_default`, `h_default`, `X_default` and `p_default`, but no `C_default`. It would be better to add `C_default = fill(0, Medium.nC)` to the MSL so that they are all consistent. Then, we can use `C_default` as the default start value and the default concentration for `Boundary_pT`, and users can reassign this value in the medium.

**Comment by Mathadon** [comment]
It's probably worth making a Modelica trac issue for this then?

**Comment by Mathadon** [comment]
@rubenbaetens can you make a Modelica trac issue?

**Comment by mwetter** [comment]
@rubenbaetens Can this issue be closed?

**Comment by rubenbaetens** [comment]
This can be closed. Issue moved to https://trac.modelica.org/Modelica/ticket/2121#ticket.
