### ISSUE TITLE
Timeline A60 1.0

### ISSUE THREAD

**Issue by Mathadon** [iea-annex60/modelica-annex60#594]
I'd like to update IDEAS to A60 1.0 for our first official release. Is there still a lot that needs to be done for this?

**Comment by mwetter** [comment]
See
https://github.com/iea-annex60/modelica-annex60/milestone/1
for the open issues. I would think around Dec. or January will be the first official release, also because this month is quite full with travel and Thanksgiving holiday.
This should also give time to have all libraries test a release candidate.
