### ISSUE TITLE
ConservationEquation does not set nominal value for U

### ISSUE THREAD

**Issue by mwetter** [iea-annex60/modelica-annex60#637]
The variable `dynBal.U` is a state in Dymola and in JModelica. There is no nominal value set for this state, although it is often around 1E5 (see below).

This issue is to set a nominal value.

A potential problem is that `U` scales with `fluidVolume`, but `fluidVolume` is not a literal parameter and hence cannot be used in Dymola to set `U.nominal`.

Below is an overview about the order of magnitude of dynBal.U for some models:
```
 5E5 (water) Annex60.Fluid.Examples.Performance.FlowSystem.Simplified6
-5E6 (air) ThreeRoomContam 
-7E5 (air, cooling coil) in Buildings.Examples.VAVAReheat.ClosedLoop
 6E5 (water, cooling coil) in same model
 1E7 to 1E8 (air, rooms) in same model
 1E6 (air, splitter) in same model
 1E4 (water, pump) in Buildings.Examples.HydronicHeating
-4E4 (air, room) in same model
 4E5 (water, radiator) in same model
 9E4 (water, valve) in same model
-1E3 (air, fan) in same model
```
Hence, we could try a nominal value of `1E5`, which should give better scaling than the default of `1`.

Note that using `T` as a state seems not be a good approach, see https://github.com/iea-annex60/modelica-annex60/issues/160

**Comment by Mathadon** [comment]
Just to be clear: U scales with `fluidVolume`, but `fluidVolume` is just a regular parameter right? The problem is also that U scales with density, which is not a literal parameter since you need to compute it using `Medium.density()`?

If that is the problem, can't we use `Medium.d_const` as an indicator for the fluid density?

**Comment by mwetter** [comment]
@Mathadon : The 'DelayFirstOrder' models assigns `fluidVolume` based on a call to the density function, which makes `fluidVolume` a non-literal parameter.

`Medium.d_constant` is not in `PartialMedium`, so not all media have this constant.

I am planning to test `U(nominal=1E5)` as it is still better than the default of `1`.

It may also be worth to run another set of reasonably sized numerical experiments to see the change in computing time if we use `T` as the state, e.g., revisit #160 compared to using `U` with `U(nominal=1E5)`, because comparing `T(nominal=300)` vs. `U(nominal=1)` is not the right comparison.

**Comment by Mathadon** [comment]
In that case `U(nominal=1E5)` should be fine I think.

I wonder if the nominal value makes a large difference, since I'm not sure where it is used. If it's used for the Newton solver of algebraic loops then I don't think it will make any difference since `U` is typically a state and therefore will never be solved using a Newton solver. If it's used for the Newton solver of the integrator then that's a different story.. 

A different option could be to use the specific internal energy `u` instead of `U` as the state value but overall I have the feeling that `U` would be the best candidate since there exists a linear relation between the time-derivative of `U` and algebraic variables `Q_flow`, meaning that the first order approximation (Jacobian in the integrator) is an exact representation. I know this argument is not mathematically solid, but I guess you get my point :)  

In any case we could try and find out what works best. I expect the difference to be small. I also expect that the nominal attribute will not cause a large difference in computation time since we only resolve up to an accuracy of `1e-6` typically, so loosing 5 digits in accuracy still does not get us to machine precision. (again: not a solid argument)

**Comment by mwetter** [comment]
This change is now on the `Buildings` master. I suggest we add it to the `Annex60` master as well, and separately see whether using `T` as a state is preferably. In either case, while not perfect, the new value for `U(nominal)` is closer to what `U` is than the default of `1`.

**Comment by Mathadon** [comment]
I did a quick test with 

`Annex60.Airflow.Multizone.Examples.OneEffectiveAirLeakageArea`
original model: 378 function evaluations
with U = 1e4: 378 function evaluations
with U = 1e5: 366 function evaluations
with U = 1e6: 367 function evaluations
with U = 1e7: 327 function evaluations
with U = 1e8: 295 function evaluations
with U = 1e9: 276 function evaluations
with U = 1e10: 273 function evaluations

at the same time however the results get worse: 

![screen shot 2016-12-23 at 09 18 32](https://cloud.githubusercontent.com/assets/5970879/21449753/d17e3042-c8f0-11e6-9cbf-6b73ebbbdb89.png)

so U(nominal) may be used to scale the convergence criterion.


`Annex60.Airflow.Multizone.Examples.ReverseBuoyancy3Zones`
original model: 4697 function evaluations
with U = 1e5: 4697 function evaluations
with U = 1e10: 4668 function evaluations

so for larger models we don't need to expect miracles :)

**Comment by Mathadon** [comment]
Using 

```
Medium.Temperature T(stateSelect=StateSelect.prefer) =   Medium.temperature_phX(p=p, h=hOut_internal, X=cat(1,Xi,{1-sum(Xi)}))
    "Temperature of the fluid";
```

results in 298 and 4668 iterations for both models with `U(nominal=1e5)`.

`Annex60.Fluid.MixingVolumes.Validation.MoistureMixingConservationDynamicBalance` yields the same number of evaluations and conservation of energy numerical error.
