### ISSUE TITLE
Implement a scalable benchmark test for air flow networks

### ISSUE THREAD

**Issue by marcusfuchs** [iea-annex60/modelica-annex60#82]
The aim of this issue is to define a benchmark test for air flow networks. The benchmark should consist of a basic system which can be multiplied in order to make the test case scalable in problem size. 
Outline:
- Define benchmark test case
- Implement test case in Modelica
- Analyze results
- Document test case and reference results

**Comment by marcusfuchs** [comment]
I pushed further commits that implement a first working version of an air flow benchmark in Experimental.Benchmarks.AirFlow.MultipleFloorsVectors that also take the wind pressure from the outside into account. I am looking forward to discuss the next steps on the upcoming conference call.

**Comment by mwetter** [comment]
@marcusfuchs 
In `Annex60.Airflow.Multizone.ZoneHallway`, you set the height of `col2` and `col3` to be equal to `heightRoom/2`.
For such large an opening, it is debatable what a good height would be, but in view of a finite difference discretization, I think `heightRoom/4` would be more appropriate. See the image of the side-view below which discretizes the room height into 4 compartments and adds flow path at `h/4`, `h/2` and `3h/4`. The flow path at `h/2` can in my view be neglected because there is no buoyancy force across two rooms at this height, and any static pressure difference between rooms is quickly eliminated through flow at the other two orifices.
```
   ----------  - center + h/2
  |            | - center + h/4
  |  room      | - center of room
  |            | - center - h/4
  ----------- - center - h/2
```
`Annex60.Airflow.Multizone.MediumColumn` uses an `outer system` declaration. This seems to be a very old version of the model. There should be no `system` be needed anymore.

The models `SimpleZone`, `ZoneHallway`, `StairCase` and `Floor` should be moved to `Annex60.Experimental.Benchmarks.AirFlow.BaseClasses` as these are only useful for the benchmarks but not for other applications (I believe).

`MediumColumn` and the door model still use a density that is independent of temperature (if `Annex60.Media.Air` is used). They should be updated with the latest version of the `Buildings` library.

The rooms and the hallway use a fixed temperature boundary condition and a thermal conductance of 1E9. This also affects the numerics. I think a more representative model would be
- to have a UA value that roughly corresponds to what a room or hallway would have, 
- connect it to the outside air temperature from the weather bus, and
- set `mSenFac` of the volume to a value that gives a time constant of a few hours.  This way, we approximate the room dynamics by a first order model.

Otherwise the models seem to be OK for the benchmarks.

**Comment by marcusfuchs** [comment]
Thanks for you comments, I will address these in the coming days.

**Comment by mwetter** [comment]
Closed as this is now on the master.
